### ISSUE TITLE
Suggestion: add category to Basics

### ISSUE THREAD

**Issue by philippe-hawi** [Dijji/CustomWindowsProperties#3]
Currently, under Basics, the property name should have the format Category.Property.
It could be more intuitive to separate them into 2 fields, Category name and Property name.

**Comment by Dijji** [comment]
Actually, valid property names can have any number of levels, for example:

Name1.NameB.Name7.Basil

At each level, the name must begin with a capital letter, and otherwise consist of upper case and lower case letters, or numbers.

I should put this in the help!

If you saved the above name, all levels of the name should appear at once the tree on the left.

You should then be able to add any or all of:
Name1.Fred
Name1.NameB.Name7.Joe
Name1.NameB.Peter
Name1.Zzzz.Alan 

But not
Name1.NameB.Name7
Name1.NameB

**Comment by philippe-hawi** [comment]
Right, I forgot about multilevels. In that case, the current design makes more sense.
